### ISSUE TITLE
Couldn't start kogma service

### ISSUE THREAD

**Issue by OssamaTammam** [losslesspng/SetUpKomgaJava#3]
Start-Service : Service 'Komga Service (komga)' cannot be started due to the following error: Cannot start service komga on computer '.'.
At line:261 char:1
+ Start-Service -Name "$serviceName"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

This is the error i get

**Comment by losslesspng** [comment]
Are you running a Microsoft account to sign into Windows? It seems there is a new security setting (not sure how recent tbh) that prevents just using the password to log in by default. If you can go to Settings>Accounts>Sign In Options and change "Require Windows Hello Sign in" to off and then try to run the service again, it should work. I just used my test machine to try signing in with a Microsoft account and got it to work this way, you may need to sign out and sign back in for it to take effect.
![image](https://user-images.githubusercontent.com/72284582/172637896-97fe448a-a5e5-4248-9c87-7a2f402159bc.png)
With this off, you should be able to start the service, and once the service is running it seems like you can turn the setting back on if you want, I have rebooted my test machine and service is still working.

**Comment by OssamaTammam** [comment]
I tried to use the local windows account and it worked but it started as a new kogma server but that's fine as long as it's working without error
