### ISSUE TITLE
Error im getting opening the script for the first time.

### ISSUE THREAD

**Issue by MeanXBeam** [losslesspng/SetUpKomgaJava#5]
PS C:\WINDOWS\system32> D:\SetUpKomgaJava-main\SetUpKomgaJava.ps1
Thanks for checking out Komga, hope you love it!
Deleting existing java folder
Starting download of OpenJDK17U-jre_x64_windows_hotspot_17.0.3_7.zip
Extracting and deleting zip file C:\Utilities\komga\OpenJDK17U-jre_x64_windows_hotspot_17.0.3_7.zip
Starting download of komga-0.157.2.jar

    Directory: C:\Utilities\komga

Mode                 LastWriteTime         Length Name                                                                                                                                                                              
----                 -------------         ------ ----                                                                                                                                                                              
-a----        10/10/2022   9:22 PM              0 UpdateKomga.ps1                                                                                                                                                                   
-a----        10/10/2022   9:22 PM              0 KomgaService.bat                                                                                                                                                                  

Actions            : {MSFT_TaskExecAction}
Author             : 
Date               : 
Description        : Check for komga updates
Documentation      : 
Principal          : MSFT_TaskPrincipal2
SecurityDescriptor : 
Settings           : MSFT_TaskSettings3
Source             : 
State              : Ready
TaskName           : Update Komga
TaskPath           : \
Triggers           : 
URI                : \Update Komga
Version            : 
PSComputerName     : 

Starting the service... Give Komga some time to start up and then access your browser at http://localhost:8080/
Start-Service : Service 'Komga Service (komga)' cannot be started due to the following error: Cannot start service komga on computer '.'.
At D:\SetUpKomgaJava-main\SetUpKomgaJava.ps1:298 char:1
+ Start-Service -Name "$serviceName"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
 
This script will automatically launch the web UI in 30 seconds or you can close it and launch it yourself.

![image](https://user-images.githubusercontent.com/107820324/194976545-14161cd9-3ca5-4721-9d05-9717c030c263.png)

**Comment by losslesspng** [comment]
Are you using a Microsoft account to log in?

**Comment by MeanXBeam** [comment]
yes i turned off the windows hello thing
